version: '3.7'

services:
  backend:
    container_name: todo-app-backend
    build: ./web
    tty: true
    restart: always
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: .
        target: /backend
    depends_on:
      - db
    networks:
      - backend_net
  db:
    container_name: todo-app-db
    build: ./db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - backend_net

networks:
  backend_net:
    external: true